version: "3"

services:
  app:
    build:
      context: .
    ports:
    - "8000:8000"
    volumes:
    - ./app:/app
    command: >
      sh -c "python main.py"
    environment:
      - DB_HOST=db
      - DB_NAME=app
      - DB_USER=sqlite
      - DB_PASS=password
    depends_on:
      - db

  db:
    image: nouchka/sqlite3:latest
    stdin_open: true
    tty: true
    # volumes:
    #   - ./db/:/root/db/
    environment:
      - SQLITE_DB=app
      - SQLITE_USER=sqlite
      - SQLITE_PASSWORD=password
